/**
 * Production build and CDN deployment script per M12-T07.
 *
 * This module provides configuration for:
 *   1. Production build optimization (Vite)
 *   2. CDN deployment configuration
 *   3. Cache-busting manifest generation
 *   4. Asset integrity hashes
 *   5. Environment-specific configuration
 */

export interface BuildConfig {
  environment: 'development' | 'staging' | 'production';
  sourceMaps: boolean;
  minify: boolean;
  chunkSizeWarningLimit: number; // KB
  assetInliningLimit: number; // bytes
  basePath: string;
  cdnUrl: string | null;
}

export const BUILD_CONFIGS: Record<BuildConfig['environment'], BuildConfig> = {
  development: {
    environment: 'development',
    sourceMaps: true,
    minify: false,
    chunkSizeWarningLimit: 2000,
    assetInliningLimit: 4096,
    basePath: '/',
    cdnUrl: null,
  },
  staging: {
    environment: 'staging',
    sourceMaps: true,
    minify: true,
    chunkSizeWarningLimit: 1000,
    assetInliningLimit: 4096,
    basePath: '/',
    cdnUrl: 'https://staging-cdn.giza.example.com',
  },
  production: {
    environment: 'production',
    sourceMaps: false,
    minify: true,
    chunkSizeWarningLimit: 500,
    assetInliningLimit: 4096,
    basePath: '/',
    cdnUrl: 'https://cdn.giza.example.com',
  },
};

// ─── Vite build configuration ──────────────────────────────────────────────

export interface ViteBuildOptions {
  outDir: string;
  assetsDir: string;
  sourcemap: boolean | 'hidden';
  minify: 'terser' | 'esbuild' | false;
  chunkSizeWarningLimit: number;
  rollupOptions: {
    output: {
      manualChunks: Record<string, string[]>;
      assetFileNames: string;
      chunkFileNames: string;
      entryFileNames: string;
    };
  };
}

/**
 * Returns Vite build options for the given environment.
 */
export function getViteBuildOptions(config: BuildConfig): ViteBuildOptions {
  return {
    outDir: 'dist',
    assetsDir: 'assets',
    sourcemap: config.sourceMaps ? (config.environment === 'production' ? false : true) : false,
    minify: config.minify ? 'terser' : false,
    chunkSizeWarningLimit: config.chunkSizeWarningLimit,
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-three': ['three', '@react-three/fiber', '@react-three/drei'],
          'vendor-state': ['zustand', 'zod'],
          'vendor-utils': ['vitest', '@testing-library/react'],
        },
        assetFileNames: 'assets/[name].[hash][extname]',
        chunkFileNames: 'assets/[name].[hash].js',
        entryFileNames: 'assets/[name].[hash].js',
      },
    },
  };
}

// ─── Cache-busting manifest ────────────────────────────────────────────────

export type AssetManifest = Record<
  string,
  {
    hashedPath: string;
    integrity: string;
    size: number;
  }
>;

/**
 * Generates an asset manifest for cache-busting.
 * In production, this is generated by the build process.
 */
export function generateManifestPlaceholder(): AssetManifest {
  return {};
}

// ─── CDN deployment configuration ──────────────────────────────────────────

export interface CDNConfig {
  provider: 'cloudflare' | 'aws-cloudfront' | 'azure-cdn' | 'custom';
  url: string;
  cacheMaxAge: number; // seconds
  cacheMaxAgeHTML: number; // seconds (shorter for HTML)
  enableCompression: boolean;
  enableBrotli: boolean;
  headers: Record<string, string>;
}

export const DEFAULT_CDN_CONFIG: CDNConfig = {
  provider: 'cloudflare',
  url: 'https://cdn.giza.example.com',
  cacheMaxAge: 31536000, // 1 year for hashed assets
  cacheMaxAgeHTML: 300, // 5 minutes for HTML
  enableCompression: true,
  enableBrotli: true,
  headers: {
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'SAMEORIGIN',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'geolocation=(), microphone=(), camera=()',
  },
};

// ─── Deployment script ────────────────────────────────────────────────────

export interface DeploymentStep {
  name: string;
  command: string;
  description: string;
}

export const DEPLOYMENT_STEPS: DeploymentStep[] = [
  {
    name: 'typecheck',
    command: 'npm run typecheck',
    description: 'TypeScript strict type checking',
  },
  {
    name: 'lint',
    command: 'npm run lint',
    description: 'ESLint code quality check',
  },
  {
    name: 'test',
    command: 'npm run test',
    description: 'Unit and integration tests',
  },
  {
    name: 'governance',
    command: 'npm run governance',
    description: 'Specification modification smoke test',
  },
  {
    name: 'build',
    command: 'npm run build',
    description: 'Production build with Vite',
  },
  {
    name: 'deploy',
    command: 'npx wrangler pages deploy dist',
    description: 'Deploy to Cloudflare Pages',
  },
];

/**
 * Returns the deployment steps for a given environment.
 */
export function getDeploymentSteps(environment: BuildConfig['environment']): DeploymentStep[] {
  if (environment === 'development') {
    return DEPLOYMENT_STEPS.filter((s) => s.name !== 'deploy');
  }
  return DEPLOYMENT_STEPS;
}

// ─── Environment variables ─────────────────────────────────────────────────

export interface EnvVars {
  VITE_API_URL: string;
  VITE_CDN_URL: string;
  VITE_ANALYTICS_ID: string;
  VITE_SENTRY_DSN: string;
  VITE_ENVIRONMENT: string;
}

export const ENV_TEMPLATES: Record<BuildConfig['environment'], EnvVars> = {
  development: {
    VITE_API_URL: 'http://localhost:3000',
    VITE_CDN_URL: '',
    VITE_ANALYTICS_ID: '',
    VITE_SENTRY_DSN: '',
    VITE_ENVIRONMENT: 'development',
  },
  staging: {
    VITE_API_URL: 'https://api.staging.giza.example.com',
    VITE_CDN_URL: 'https://staging-cdn.giza.example.com',
    VITE_ANALYTICS_ID: 'staging-analytics-id',
    VITE_SENTRY_DSN: 'https://sentry-staging.example.com',
    VITE_ENVIRONMENT: 'staging',
  },
  production: {
    VITE_API_URL: 'https://api.giza.example.com',
    VITE_CDN_URL: 'https://cdn.giza.example.com',
    VITE_ANALYTICS_ID: 'production-analytics-id',
    VITE_SENTRY_DSN: 'https://sentry-production.example.com',
    VITE_ENVIRONMENT: 'production',
  },
};
