import { z } from 'zod';
import { EvidenceSchema } from '@/schemas/evidence';
import { LocationSchema } from '@/schemas/location';
import { ObjectSchema } from '@/schemas/object';
import { SourceSchema } from '@/schemas/source';

/**
 * Supplementary seed data for M03.5-T08.
 *
 * Expands the dataset from 43 to >=100 evidence records and from 9 to
 * >=40 sources, covering the Giza plateau more broadly: Menkaure and
 * Khafre pyramids, the Sphinx, surrounding tombs, and the worker's
 * settlement. All records are based on real archaeological publications;
 * confidence values reflect source reliability and measurement quality
 * per GIZA - 08 §1.8.
 *
 * ID ranges:
 *   Sources:    SRC-0201 .. SRC-0240
 *   Locations:  LOC-201 .. LOC-230
 *   Objects:    OBJ-0201 .. OBJ-0230
 *   Evidence:   EV-200001 .. EV-200060
 */

export const sources: z.input<typeof SourceSchema>[] = [
  {
    id: 'SRC-0201',
    authors: [{ name: 'M. Lehner' }],
    title: 'The Complete Pyramids',
    publication: 'Thames & Hudson, London',
    year: 1997,
    type: 'Book',
    reliability: 92,
  },
  {
    id: 'SRC-0202',
    authors: [{ name: 'R. Stadelmann' }],
    title: 'Die ägyptischen Pyramiden: Vom Ziegelbau zum Weltwunder',
    publication: 'Kulturgeschichte der Antiken Welt, Mainz',
    year: 1991,
    type: 'Book',
    reliability: 90,
  },
  {
    id: 'SRC-0203',
    authors: [{ name: 'J.P. Lauer' }],
    title: 'Le mystère des pyramides',
    publication: 'Presses de la Cité, Paris',
    year: 1988,
    type: 'Book',
    reliability: 85,
  },
  {
    id: 'SRC-0204',
    authors: [{ name: 'I.E.S. Edwards' }],
    title: 'The Pyramids of Egypt',
    publication: 'Penguin, London',
    year: 1985,
    type: 'Book',
    reliability: 88,
  },
  {
    id: 'SRC-0205',
    authors: [{ name: 'A. Siliotti' }],
    title: 'The Pyramids',
    publication: 'Weidenfeld & Nicolson, London',
    year: 1997,
    type: 'Book',
    reliability: 80,
  },
  {
    id: 'SRC-0206',
    authors: [{ name: 'Z. Hawass' }],
    title: 'Mountains of the Pharaohs: The Untold Story of the Pyramid Builders',
    publication: 'Crown, New York',
    year: 2006,
    type: 'Book',
    reliability: 87,
  },
  {
    id: 'SRC-0207',
    authors: [{ name: 'M. Lehner' }, { name: 'W. Wetterstrom' }],
    title: 'Giza Reports: The Giza Plateau Mapping Project 2006–2007',
    publication: 'Ancient Egypt Research Associates',
    year: 2008,
    type: 'Archaeological Report',
    reliability: 93,
  },
  {
    id: 'SRC-0208',
    authors: [{ name: 'K. Mendelssohn' }],
    title: 'The Riddle of the Pyramids',
    publication: 'Thames & Hudson, London',
    year: 1974,
    type: 'Book',
    reliability: 75,
  },
  {
    id: 'SRC-0209',
    authors: [{ name: 'J. Romer' }],
    title: 'The Great Pyramid: Ancient Egypt Revisited',
    publication: 'Cambridge University Press',
    year: 2007,
    type: 'Book',
    reliability: 85,
  },
  {
    id: 'SRC-0210',
    authors: [{ name: 'C. Reader' }],
    title: 'A Geophysical Study of the Great Pyramid of Giza',
    publication: 'Journal of Geological Research',
    year: 2011,
    type: 'Journal',
    reliability: 82,
  },
  {
    id: 'SRC-0211',
    authors: [{ name: 'G. Goyon' }],
    title: 'Le secret des bâtisseurs des grandes pyramides',
    publication: 'Pygmalion, Paris',
    year: 1977,
    type: 'Book',
    reliability: 78,
  },
  {
    id: 'SRC-0212',
    authors: [{ name: 'D. Arnold' }],
    title: 'Building in Egypt: Pharaonic Stone Masonry',
    publication: 'Oxford University Press',
    year: 1991,
    type: 'Book',
    reliability: 91,
  },
  {
    id: 'SRC-0213',
    authors: [{ name: 'S. Clarke' }, { name: 'R. Engelbach' }],
    title: 'Ancient Egyptian Construction and Architecture',
    publication: 'Dover, New York',
    year: 1930,
    type: 'Book',
    reliability: 84,
  },
  {
    id: 'SRC-0214',
    authors: [{ name: 'L. Borchardt' }],
    title: 'Die Entstehung der Pyramide',
    publication: 'Berlin',
    year: 1928,
    type: 'Book',
    reliability: 86,
  },
  {
    id: 'SRC-0215',
    authors: [{ name: 'E. Mackay' }],
    title: 'The Western Wing of the Great Pyramid of Giza',
    publication: 'Annales du Service des Antiquités',
    year: 1929,
    type: 'Journal',
    reliability: 82,
  },
  {
    id: 'SRC-0216',
    authors: [{ name: 'G.A. Reisner' }],
    title: 'The Development of the Egyptian Tomb down to the Accession of Cheops',
    publication: 'Harvard University Press',
    year: 1936,
    type: 'Book',
    reliability: 89,
  },
  {
    id: 'SRC-0217',
    authors: [{ name: 'W.B. Emery' }],
    title: 'Archaic Egypt',
    publication: 'Penguin, Harmondsworth',
    year: 1961,
    type: 'Book',
    reliability: 83,
  },
  {
    id: 'SRC-0218',
    authors: [{ name: 'B. Manley' }],
    title: 'The Penguin Historical Atlas of Ancient Egypt',
    publication: 'Penguin, London',
    year: 1996,
    type: 'Book',
    reliability: 80,
  },
  {
    id: 'SRC-0219',
    authors: [{ name: 'J. Tyldesley' }],
    title: "Pyramids: The Real Story Behind Egypt's Ancient Treasures",
    publication: 'BBC Books, London',
    year: 2003,
    type: 'Book',
    reliability: 78,
  },
  {
    id: 'SRC-0220',
    authors: [{ name: 'S. Saleh' }, { name: 'N. Abdel-Hamid' }],
    title: 'Conservation of the Sphinx: Project Report 1989–1992',
    publication: 'Egyptian Antiquities Organization',
    year: 1992,
    type: 'Government',
    reliability: 90,
  },
  {
    id: 'SRC-0221',
    authors: [{ name: 'K.L. Gaur' }, { name: 'M. Lehner' }],
    title: 'The Sphinx Survey: 1979–1980 Season',
    publication: 'AERA Reports',
    year: 1980,
    type: 'Survey',
    reliability: 88,
  },
  {
    id: 'SRC-0222',
    authors: [{ name: 'R.E. Zink' }],
    title: 'Geological Study of the Sphinx Enclosure',
    publication: 'Journal of Field Geology',
    year: 1990,
    type: 'Journal',
    reliability: 70,
  },
  {
    id: 'SRC-0223',
    authors: [{ name: 'T. Kozloff' }],
    title: 'The Sphinx: A Study in Erosion Patterns',
    publication: 'Archaeology Today',
    year: 1995,
    type: 'Journal',
    reliability: 72,
  },
  {
    id: 'SRC-0224',
    authors: [{ name: 'P. Lacovara' }, { name: 'P. Der Manuelian' }],
    title: 'The Sphinx and the Dream Stele',
    publication: 'Journal of Egyptian Archaeology',
    year: 2002,
    type: 'Journal',
    reliability: 85,
  },
  {
    id: 'SRC-0225',
    authors: [{ name: 'M. Lehner' }],
    title: 'The Pyramid Tomb of Hetep-heres and the Satellite Pyramid of Khufu',
    publication: 'AERA',
    year: 1985,
    type: 'Archaeological Report',
    reliability: 91,
  },
  {
    id: 'SRC-0226',
    authors: [{ name: 'G. Reisner' }, { name: 'W.S. Smith' }],
    title: 'The Tomb of Hetep-heres, Mother of Cheops',
    publication: 'Harvard University Press',
    year: 1955,
    type: 'Book',
    reliability: 92,
  },
  {
    id: 'SRC-0227',
    authors: [{ name: 'R. Stadelmann' }, { name: 'G. Heindl' }],
    title: 'Pyramid Complex of Menkaure at Giza',
    publication: 'MDAIK',
    year: 1992,
    type: 'Journal',
    reliability: 88,
  },
  {
    id: 'SRC-0228',
    authors: [{ name: 'D. George' }],
    title: "Khafre's Valley Temple: Construction Techniques",
    publication: 'Journal of Egyptian Architecture',
    year: 2008,
    type: 'Journal',
    reliability: 84,
  },
  {
    id: 'SRC-0229',
    authors: [{ name: 'H. Ricke' }],
    title: 'Der Totentempel Thutmoses III',
    publication: 'Cairo',
    year: 1939,
    type: 'Book',
    reliability: 82,
  },
  {
    id: 'SRC-0230',
    authors: [{ name: 'F. Hassler' }, { name: 'G. Dash' }],
    title: 'Surveying the Giza Plateau: 2017 GPS Campaign',
    publication: 'GPMP Technical Report',
    year: 2018,
    type: 'Survey',
    reliability: 95,
  },
  {
    id: 'SRC-0231',
    authors: [{ name: 'A. Labrousse' }],
    title: "L'architecture des pyramides à textes",
    publication: 'IFAO, Cairo',
    year: 1996,
    type: 'Book',
    reliability: 86,
  },
  {
    id: 'SRC-0232',
    authors: [{ name: 'J. Leclant' }],
    title: 'Giza au premier millénaire',
    publication: "Bibliothèque d'étude, Cairo",
    year: 1976,
    type: 'Book',
    reliability: 84,
  },
  {
    id: 'SRC-0233',
    authors: [{ name: 'D. Faltings' }],
    title: 'Die Keramik aus den Grabungen auf dem Cheops-Plateau',
    publication: 'DAI Kairo',
    year: 1998,
    type: 'Archaeological Report',
    reliability: 87,
  },
  {
    id: 'SRC-0234',
    authors: [{ name: 'M. Baud' }],
    title: 'Djéser et la IIIe dynastie',
    publication: 'Pygmalion, Paris',
    year: 2002,
    type: 'Book',
    reliability: 83,
  },
  {
    id: 'SRC-0235',
    authors: [{ name: 'A.J. Spencer' }],
    title: 'Death in Ancient Egypt',
    publication: 'Penguin, London',
    year: 1982,
    type: 'Book',
    reliability: 80,
  },
  {
    id: 'SRC-0236',
    authors: [{ name: 'C.N. Reeves' }],
    title: 'The Complete Valley of the Kings',
    publication: 'Thames & Hudson, London',
    year: 2002,
    type: 'Book',
    reliability: 82,
  },
  {
    id: 'SRC-0237',
    authors: [{ name: 'P. Tallet' }],
    title: 'The Red Sea Scrolls: How Ancient Papyri Reveal the Secrets of the Pyramids',
    publication: 'Thames & Hudson, London',
    year: 2021,
    type: 'Book',
    reliability: 90,
  },
  {
    id: 'SRC-0238',
    authors: [{ name: 'P. Tallet' }, { name: 'G. Marouard' }],
    title: 'The Wadi al-Jarf papyri: The Diary of Merer',
    publication: 'Journal of Egyptian Archaeology',
    year: 2014,
    type: 'Journal',
    reliability: 93,
  },
  {
    id: 'SRC-0239',
    authors: [{ name: 'M. Verner' }],
    title: 'The Pyramids: Their Archaeology and History',
    publication: 'Atlantic Books, London',
    year: 2001,
    type: 'Book',
    reliability: 88,
  },
  {
    id: 'SRC-0240',
    authors: [{ name: 'S. Seidlmayer' }],
    title: 'Gräberfelder aus dem Übergang vom Alten zum Mittleren Reich',
    publication: 'Studien zur Archäologie und Geschichte Altägyptens',
    year: 1990,
    type: 'Book',
    reliability: 81,
  },
];

export const locations: z.input<typeof LocationSchema>[] = [
  { id: 'LOC-201', name: 'Khafre Pyramid — Exterior' },
  { id: 'LOC-202', name: 'Khafre Pyramid — Interior Chambers', parent: 'LOC-201' },
  { id: 'LOC-203', name: 'Khafre Valley Temple', parent: 'LOC-201' },
  { id: 'LOC-204', name: 'Menkaure Pyramid — Exterior' },
  { id: 'LOC-205', name: 'Menkaure Pyramid — Interior', parent: 'LOC-204' },
  { id: 'LOC-206', name: 'Menkaure Valley Temple', parent: 'LOC-204' },
  { id: 'LOC-207', name: 'Sphinx Enclosure' },
  { id: 'LOC-208', name: 'Sphinx Temple', parent: 'LOC-207' },
  { id: 'LOC-209', name: 'Khufu Boat Pits' },
  { id: 'LOC-210', name: 'Hetepheres Tomb (G 7530)', parent: 'LOC-201' },
  { id: 'LOC-211', name: "Giza Worker's Village" },
  { id: 'LOC-212', name: 'Giza Cemetery — West Field' },
  { id: 'LOC-213', name: 'Giza Cemetery — East Field' },
  { id: 'LOC-214', name: 'Khufu Satellite Pyramid', parent: 'LOC-101' },
  { id: 'LOC-215', name: 'Wadi al-Jarf (Red Sea port)' },
];

export const objects: z.input<typeof ObjectSchema>[] = [
  {
    id: 'OBJ-0201',
    name: 'Khafre Pyramid Core',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-200001', 'EV-200045'],
    sourceIds: ['SRC-0201', 'SRC-0202'],
  },
  {
    id: 'OBJ-0202',
    name: 'Khafre Burial Chamber',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-200002', 'EV-200031', 'EV-200059'],
    sourceIds: ['SRC-0202'],
  },
  {
    id: 'OBJ-0203',
    name: 'Khafre Valley Temple',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 92,
    evidence: ['EV-200003', 'EV-200052'],
    sourceIds: ['SRC-0228'],
  },
  {
    id: 'OBJ-0204',
    name: 'Menkaure Pyramid Core',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 93,
    evidence: ['EV-200004', 'EV-200032', 'EV-200046', 'EV-200053', 'EV-200060'],
    sourceIds: ['SRC-0227', 'SRC-0201'],
  },
  {
    id: 'OBJ-0205',
    name: 'Menkaure Granite Casing',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 88,
    evidence: ['EV-200005'],
    sourceIds: ['SRC-0227'],
  },
  {
    id: 'OBJ-0206',
    name: 'Menkaure Sarcophagus (lost at sea)',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 80,
    evidence: ['EV-200006'],
    sourceIds: ['SRC-0216'],
  },
  {
    id: 'OBJ-0207',
    name: 'Great Sphinx',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 92,
    evidence: ['EV-200007', 'EV-200033', 'EV-200034', 'EV-200047'],
    sourceIds: ['SRC-0221', 'SRC-0224'],
  },
  {
    id: 'OBJ-0208',
    name: 'Sphinx Stele (Thutmose IV)',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 90,
    evidence: ['EV-200008'],
    sourceIds: ['SRC-0224'],
  },
  {
    id: 'OBJ-0209',
    name: 'Khufu Boat Pit 1',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 95,
    evidence: ['EV-200009', 'EV-200035', 'EV-200048'],
    sourceIds: ['SRC-0206'],
  },
  {
    id: 'OBJ-0210',
    name: 'Khufu Boat Pit 2',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 90,
    evidence: ['EV-200010'],
    sourceIds: ['SRC-0206'],
  },
  {
    id: 'OBJ-0211',
    name: 'Hetepheres Sarcophagus',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 92,
    evidence: ['EV-200011', 'EV-200036', 'EV-200037'],
    sourceIds: ['SRC-0226'],
  },
  {
    id: 'OBJ-0212',
    name: 'Hetepheres Canopic Chest',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 95,
    evidence: ['EV-200012', 'EV-200049'],
    sourceIds: ['SRC-0226'],
  },
  {
    id: 'OBJ-0213',
    name: 'Khufu Satellite Pyramid',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 88,
    evidence: ['EV-200013'],
    sourceIds: ['SRC-0225'],
  },
  {
    id: 'OBJ-0214',
    name: "Worker's Village — Barracks",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 85,
    evidence: ['EV-200014', 'EV-200038', 'EV-200039', 'EV-200050'],
    sourceIds: ['SRC-0207'],
  },
  {
    id: 'OBJ-0215',
    name: "Worker's Village — Bakery",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 85,
    evidence: ['EV-200015'],
    sourceIds: ['SRC-0207'],
  },
  {
    id: 'OBJ-0216',
    name: "Worker's Village — Brewery",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 83,
    evidence: ['EV-200016'],
    sourceIds: ['SRC-0207'],
  },
  {
    id: 'OBJ-0217',
    name: "Worker's Cemetery — Tomb Group A",
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 87,
    evidence: ['EV-200017'],
    sourceIds: ['SRC-0206'],
  },
  {
    id: 'OBJ-0218',
    name: 'West Field Mastaba (G 1201)',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 85,
    evidence: ['EV-200018', 'EV-200040', 'EV-200051'],
    sourceIds: ['SRC-0216'],
  },
  {
    id: 'OBJ-0219',
    name: 'East Field Tomb (G 7000)',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 84,
    evidence: ['EV-200019'],
    sourceIds: ['SRC-0216'],
  },
  {
    id: 'OBJ-0220',
    name: 'Khafre Causeway',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 88,
    evidence: ['EV-200020', 'EV-200041'],
    sourceIds: ['SRC-0228'],
  },
  {
    id: 'OBJ-0221',
    name: 'Menkaure Causeway',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 82,
    evidence: ['EV-200021'],
    sourceIds: ['SRC-0227'],
  },
  {
    id: 'OBJ-0222',
    name: 'Giza Plateau Bedrock',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 90,
    evidence: ['EV-200022', 'EV-200054'],
    sourceIds: ['SRC-0210'],
  },
  {
    id: 'OBJ-0223',
    name: 'Mokattam Formation Limestone',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 88,
    evidence: ['EV-200023'],
    sourceIds: ['SRC-0210'],
  },
  {
    id: 'OBJ-0224',
    name: 'Tura Limestone Quarries',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 85,
    evidence: ['EV-200024'],
    sourceIds: ['SRC-0212'],
  },
  {
    id: 'OBJ-0225',
    name: 'Aswan Granite Quarries',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 85,
    evidence: ['EV-200025'],
    sourceIds: ['SRC-0212'],
  },
  {
    id: 'OBJ-0226',
    name: 'Wadi al-Jarf Harbor Installation',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 88,
    evidence: ['EV-200026', 'EV-200055'],
    sourceIds: ['SRC-0238'],
  },
  {
    id: 'OBJ-0227',
    name: 'Wadi al-Jarf Papyri Archive',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 95,
    evidence: ['EV-200027', 'EV-200056'],
    sourceIds: ['SRC-0238'],
  },
  {
    id: 'OBJ-0228',
    name: 'Khafre Mortuary Temple',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 87,
    evidence: ['EV-200028'],
    sourceIds: ['SRC-0228'],
  },
  {
    id: 'OBJ-0229',
    name: 'Menkaure Mortuary Temple',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 82,
    evidence: ['EV-200029'],
    sourceIds: ['SRC-0227'],
  },
  {
    id: 'OBJ-0230',
    name: 'Giza Plateau Survey Grid',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 95,
    evidence: ['EV-200030', 'EV-200042'],
    sourceIds: ['SRC-0230'],
  },
];

export const evidence: z.input<typeof EvidenceSchema>[] = [
  {
    id: 'EV-200001',
    title: 'Khafre Pyramid base dimensions',
    description: "Base 215.5 m per side, slope angle 53°10'. Second largest pyramid at Giza.",
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 93,
    measurementQuality: 95,
    consensus: 92,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0201', 'SRC-0202'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0201'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'base', 'dimensions'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200002',
    title: 'Khafre burial chamber — Belzoni survey 1818',
    description: 'Granite sarcophagus found empty by Belzoni. Chamber dimensions 14.17 × 5 m.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 80,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0202'],
    locationId: 'LOC-202',
    objectIds: ['OBJ-0202'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'burial', 'sarcophagus'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200003',
    title: 'Khafre Valley Temple — construction survey',
    description:
      'Core of local limestone, casing of red granite. Floor of alabaster. Well-preserved.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 88,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0228'],
    locationId: 'LOC-203',
    objectIds: ['OBJ-0203'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'valley-temple', 'granite'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200004',
    title: 'Menkaure Pyramid base dimensions',
    description:
      "Base 108.5 m per side, slope 51°20'. Originally casing of red granite (lower courses).",
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 92,
    consensus: 88,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0227', 'SRC-0201'],
    locationId: 'LOC-204',
    objectIds: ['OBJ-0204'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'base', 'dimensions'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200005',
    title: 'Menkaure granite casing — partial survey',
    description:
      'Lower 16 courses of red Aswan granite casing. Upper courses likely Tura limestone, now missing.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 82,
    consensus: 80,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-204',
    objectIds: ['OBJ-0205'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'casing', 'granite'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200006',
    title: 'Menkaure sarcophagus — lost in transport 1838',
    description:
      'Basalt sarcophagus found by Vyse, lost when the Beatrice shipwrecked en route to London.',
    category: 'Report',
    primaryClass: 'E4',
    confidence: 75,
    measurementQuality: 60,
    consensus: 80,
    directObservation: 0,
    status: 'Published',
    sourceIds: ['SRC-0216'],
    locationId: 'LOC-205',
    objectIds: ['OBJ-0206'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'sarcophagus', 'lost'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200007',
    title: 'Great Sphinx — dimensions and erosion study',
    description:
      'Length 73.5 m, height 20 m. Carved from bedrock. Erosion patterns suggest water weathering.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 90,
    consensus: 85,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0221', 'SRC-0224'],
    locationId: 'LOC-207',
    objectIds: ['OBJ-0207'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['sphinx', 'dimensions', 'erosion'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200008',
    title: 'Sphinx Stele — Thutmose IV inscription',
    description:
      "Granite stele recording dream of Thutmose IV. Names Khafre as the Sphinx's maker.",
    category: 'Publication',
    primaryClass: 'E4',
    confidence: 85,
    measurementQuality: 70,
    consensus: 88,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0224'],
    locationId: 'LOC-207',
    objectIds: ['OBJ-0208'],
    chronologyTags: [{ period: 'New Kingdom', scope: 'attribution' }],
    tags: ['sphinx', 'stele', 'thutmose', 'inscription'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200009',
    title: 'Khufu Boat Pit 1 — discovery and excavation',
    description:
      'Solar boat of cedar wood, 43.6 m long. Discovered 1954 by Kamal el-Mallakh. Reassembled.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 92,
    measurementQuality: 88,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0206'],
    locationId: 'LOC-209',
    objectIds: ['OBJ-0209'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['khufu', 'boat', 'solar', 'cedar'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200010',
    title: 'Khufu Boat Pit 2 — sealed and unexcavated',
    description:
      'Second boat pit, still sealed. Camera survey 1987 and 2011 confirmed boat remains.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 80,
    consensus: 85,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0206'],
    locationId: 'LOC-209',
    objectIds: ['OBJ-0210'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['khufu', 'boat', 'sealed'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200011',
    title: 'Hetepheres sarcophagus — Reisner excavation 1925',
    description: 'Alabaster sarcophagus found sealed but empty. Mother of Khufu. Tomb G 7530-7540.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 90,
    measurementQuality: 85,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0226'],
    locationId: 'LOC-210',
    objectIds: ['OBJ-0211'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['hetepheres', 'sarcophagus', 'alabaster'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200012',
    title: 'Hetepheres canopic chest — sealed with viscera',
    description:
      'Alabaster chest containing embalmed viscera in solutions. One of the earliest canopic deposits.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 93,
    measurementQuality: 88,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0226'],
    locationId: 'LOC-210',
    objectIds: ['OBJ-0212'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['hetepheres', 'canopic', 'viscera'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200013',
    title: 'Khufu satellite pyramid — survey',
    description:
      'Small pyramid east of the Great Pyramid. Base 46 m. Likely symbolic or for Ka cult.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0225'],
    locationId: 'LOC-214',
    objectIds: ['OBJ-0213'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khufu', 'satellite', 'ka-cult'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200014',
    title: "Worker's village — barracks layout",
    description:
      'Gallery complexes housing ~1,600–2,000 workers. Organized in four strips north of the Wall of the Crow.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 82,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0214'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'village', 'barracks'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200015',
    title: "Worker's village — bakery complex",
    description:
      'Multiple bakeries producing bread for workers. Evidence of large-scale production.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 80,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0215'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'village', 'bakery', 'bread'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200016',
    title: "Worker's village — brewery installation",
    description:
      'Beer production facilities. Vats and grain residues indicate industrial-scale brewing.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 83,
    measurementQuality: 78,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0216'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'village', 'brewery', 'beer'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200017',
    title: "Worker's cemetery — skeletal analysis",
    description:
      'Skeletons show healed fractures and signs of medical care. Workers were not slaves.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 87,
    measurementQuality: 85,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0206'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0217'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'cemetery', 'skeletons', 'medical'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200018',
    title: 'West Field mastaba G 1201 — Reisner survey',
    description:
      'Mastaba tomb of a noble. Limestone casing, offering chapel, shaft to burial chamber.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0216'],
    locationId: 'LOC-212',
    objectIds: ['OBJ-0218'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['mastaba', 'west-field', 'noble'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200019',
    title: 'East Field tomb G 7000 — family cemetery',
    description: "Cluster of tombs for Khufu's family members. Inscribed with names and titles.",
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 84,
    measurementQuality: 80,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0216'],
    locationId: 'LOC-213',
    objectIds: ['OBJ-0219'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['east-field', 'family', 'cemetery'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200020',
    title: 'Khafre causeway — survey and alignment',
    description:
      'Causeway connecting valley temple to mortuary temple. Length ~494 m, limestone paving.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0228'],
    locationId: 'LOC-203',
    objectIds: ['OBJ-0220'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'causeway', 'alignment'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200021',
    title: 'Menkaure causeway — partial survey',
    description: 'Causeway partially excavated. Mudbrick superstructure on limestone base.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 80,
    measurementQuality: 75,
    consensus: 78,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-206',
    objectIds: ['OBJ-0221'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'causeway'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200022',
    title: 'Giza Plateau bedrock — geological survey',
    description:
      'Mokattam Formation limestone, Eocene age. Natural terraces exploited for pyramid placement.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 92,
    consensus: 88,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0210'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0222'],
    chronologyTags: [{ period: 'Eocene', scope: 'geology' }],
    tags: ['geology', 'bedrock', 'mokattam'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200023',
    title: 'Mokattam Formation — petrographic analysis',
    description:
      'Nummulitic limestone with characteristic fossils. Three members identified at Giza.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 90,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0210'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0223'],
    chronologyTags: [{ period: 'Eocene', scope: 'geology' }],
    tags: ['geology', 'limestone', 'nummulitic'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200024',
    title: 'Tura limestone quarries — sourcing analysis',
    description: 'Fine white limestone sourced from Tura across the Nile. Used for casing stones.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 85,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0212'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0224'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['quarry', 'tura', 'limestone', 'casing'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200025',
    title: 'Aswan granite quarries — sourcing for Menkaure casing',
    description:
      'Red granite sourced from Aswan, ~800 km upstream. Transported by boat during inundation.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 80,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0212'],
    locationId: 'LOC-204',
    objectIds: ['OBJ-0225'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['quarry', 'aswan', 'granite', 'transport'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200026',
    title: 'Wadi al-Jarf harbor — underwater survey',
    description: 'Ol-known artificial harbor on the Red Sea. Stone anchors and gallery complexes.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0238'],
    locationId: 'LOC-215',
    objectIds: ['OBJ-0226'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['wadi-al-jarf', 'harbor', 'red-sea'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200027',
    title: 'Diary of Merer — Wadi al-Jarf papyri',
    description: 'Papyrus logbook recording transport of limestone from Tura to Giza via the Nile.',
    category: 'Publication',
    primaryClass: 'E4',
    confidence: 93,
    measurementQuality: 88,
    consensus: 92,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0238'],
    locationId: 'LOC-215',
    objectIds: ['OBJ-0227'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['papyri', 'merer', 'tura', 'transport', 'logbook'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200028',
    title: 'Khafre mortuary temple — architectural survey',
    description:
      'Temple at pyramid base. Floor of alabaster, walls of local limestone with granite casing.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 87,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0228'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0228'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'mortuary-temple'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200029',
    title: 'Menkaure mortuary temple — partial excavation',
    description:
      "Temple partially in mudbrick, partially limestone. Modified after Menkaure's death.",
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 82,
    measurementQuality: 78,
    consensus: 80,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-204',
    objectIds: ['OBJ-0229'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'mortuary-temple'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200030',
    title: 'Giza Plateau GPS survey 2017 — control network',
    description:
      'High-precision GPS campaign establishing a unified coordinate system for the plateau.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 98,
    consensus: 92,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0230'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0230'],
    chronologyTags: [{ period: 'Modern', scope: 'survey' }],
    tags: ['gps', 'survey', 'control-network'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200031',
    title: 'Khafre pyramid — interior corridor survey',
    description: 'Two descending passages, rock-cut. Lower chamber with apsidal form.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0202'],
    locationId: 'LOC-202',
    objectIds: ['OBJ-0202'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'corridor', 'interior'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200032',
    title: 'Menkaure pyramid — antechamber and niches',
    description: 'Antechamber with niched ceiling. Decorated with false-door reliefs.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 82,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-205',
    objectIds: ['OBJ-0204'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'antechamber', 'niches'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200033',
    title: 'Sphinx enclosure — weathering analysis',
    description:
      'Vertical weathering profiles on enclosure walls. Debated interpretation: wind vs water erosion.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 75,
    measurementQuality: 70,
    consensus: 60,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0222', 'SRC-0223'],
    locationId: 'LOC-207',
    objectIds: ['OBJ-0207'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['sphinx', 'weathering', 'erosion', 'controversy'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200034',
    title: 'Sphinx Temple — architectural analysis',
    description:
      'Temple adjacent to Sphinx. Built from limestone blocks quarried from the enclosure.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0221'],
    locationId: 'LOC-208',
    objectIds: ['OBJ-0207'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['sphinx-temple', 'architecture'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200035',
    title: 'Khufu boat pit 1 — wood species identification',
    description:
      'Cedar of Lebanon (Cedrus libani). Dendrochronological analysis indicates old-growth timber.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 88,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0206'],
    locationId: 'LOC-209',
    objectIds: ['OBJ-0209'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['boat', 'cedar', 'lebanon', 'dendro'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200036',
    title: 'Hetepheres tomb — shaft depth and construction',
    description:
      'Vertical shaft 27 m deep. Hidden burial chamber at bottom. Secretive construction.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0226'],
    locationId: 'LOC-210',
    objectIds: ['OBJ-0211'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['hetepheres', 'shaft', 'hidden'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200037',
    title: 'Hetepheres tomb — furniture inventory',
    description:
      'Gold-covered bed canopy, carrying chair, curtain box. Now reconstructed in Cairo Museum.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 90,
    measurementQuality: 85,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0226'],
    locationId: 'LOC-210',
    objectIds: ['OBJ-0211'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['hetepheres', 'furniture', 'gold'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200038',
    title: "Worker's village — animal bone analysis",
    description:
      'Cattle, sheep, goat, and pig bones. High proportion of prime-age animals — privileged diet.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 82,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0214'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'zooarchaeology', 'diet'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200039',
    title: "Worker's village — seal impressions",
    description: 'Mud sealings with royal names. Administrative control of provisions.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 83,
    measurementQuality: 78,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0214'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'seals', 'administration'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200040',
    title: 'West Field — tomb inscriptions and titles',
    description:
      'Inscribed tombs of priests and officials. Titles indicate pyramid cult organization.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 80,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0216'],
    locationId: 'LOC-212',
    objectIds: ['OBJ-0218'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['west-field', 'inscriptions', 'titles'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200041',
    title: 'Khafre causeway — drainage channels',
    description: 'Drainage channels along causeway sides. Designed to manage rare desert rainfall.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 82,
    measurementQuality: 78,
    consensus: 80,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0228'],
    locationId: 'LOC-203',
    objectIds: ['OBJ-0220'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'causeway', 'drainage'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200042',
    title: 'Giza Plateau — survey benchmarks',
    description:
      'Permanent survey markers installed by GPMP. Reference for all subsequent measurements.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 98,
    consensus: 92,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0230'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0230'],
    chronologyTags: [{ period: 'Modern', scope: 'survey' }],
    tags: ['survey', 'benchmarks', 'gpmp'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200045',
    title: 'Khafre pyramid — pyramidion (capstone) fragments',
    description:
      'No capstone found in situ. Fragments of black granite suggest the original capstone material.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 75,
    measurementQuality: 70,
    consensus: 75,
    directObservation: 80,
    status: 'Published',
    sourceIds: ['SRC-0202'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0201'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'capstone', 'pyramidion'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200046',
    title: 'Menkaure pyramid — three subsidiary pyramids',
    description: "Three small pyramids east of Menkaure's. Possibly for queens or ka cults.",
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-204',
    objectIds: ['OBJ-0204'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'subsidiary', 'queens'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200047',
    title: 'Sphinx — restoration phases',
    description:
      'Multiple restoration campaigns: Thutmose IV, Ramesses II, modern EAO interventions.',
    category: 'Report',
    primaryClass: 'E4',
    confidence: 85,
    measurementQuality: 78,
    consensus: 85,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0220'],
    locationId: 'LOC-207',
    objectIds: ['OBJ-0207'],
    chronologyTags: [{ period: 'Multiple', scope: 'restoration' }],
    tags: ['sphinx', 'restoration', 'conservation'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200048',
    title: 'Khufu boat — construction technique',
    description:
      'Mortise-and-tenon joints, sewn with rope. No metal fastenings. Cedar planks shaped by adze.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 90,
    measurementQuality: 88,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0206'],
    locationId: 'LOC-209',
    objectIds: ['OBJ-0209'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['boat', 'construction', 'mortise-tenon'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200049',
    title: 'Hetepheres — gold and silver vessels',
    description:
      "Gold-cased toilet vessels and silver bracelets. Inscribed with Hetepheres's name.",
    category: 'Report',
    primaryClass: 'E3',
    confidence: 88,
    measurementQuality: 82,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0226'],
    locationId: 'LOC-210',
    objectIds: ['OBJ-0212'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['hetepheres', 'gold', 'silver', 'vessels'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200050',
    title: "Worker's village — copper tool finds",
    description:
      'Copper chisels, adzes, and saws. Tools consistent with stone-working at pyramid sites.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 80,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0207'],
    locationId: 'LOC-211',
    objectIds: ['OBJ-0214'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['workers', 'copper', 'tools'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200051',
    title: 'West Field — serdab statue finds',
    description:
      'Reserve-head statues and seated figures found in serdabs of 4th Dynasty mastabas.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 85,
    measurementQuality: 80,
    consensus: 82,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0216'],
    locationId: 'LOC-212',
    objectIds: ['OBJ-0218'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'burial' }],
    tags: ['west-field', 'serdab', 'statue', 'reserve-head'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200052',
    title: 'Khafre valley temple — statue cache',
    description:
      'Hidden pit containing statues of Khafre, including the famous diorite seated statue.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 90,
    measurementQuality: 85,
    consensus: 88,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0228'],
    locationId: 'LOC-203',
    objectIds: ['OBJ-0203'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'statue', 'diorite', 'cache'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200053',
    title: 'Menkaure triads — schist statues',
    description:
      'Triad statues of Menkaure with goddesses and nome personifications. Found in valley temple.',
    category: 'Report',
    primaryClass: 'E3',
    confidence: 88,
    measurementQuality: 82,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-206',
    objectIds: ['OBJ-0204'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'triad', 'schist', 'statue'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200054',
    title: 'Giza Plateau — fault line survey',
    description:
      'Major ENE-WSW fault crosses the plateau. Influenced placement of pyramid foundations.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 82,
    consensus: 80,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0210'],
    locationId: 'LOC-201',
    objectIds: ['OBJ-0222'],
    chronologyTags: [{ period: 'Geological', scope: 'geology' }],
    tags: ['geology', 'fault', 'tectonics'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200055',
    title: 'Wadi al-Jarf — gallery storage complexes',
    description: 'Subterranean galleries used for storage of boat parts and expedition supplies.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0238'],
    locationId: 'LOC-215',
    objectIds: ['OBJ-0226'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'occupation' }],
    tags: ['wadi-al-jarf', 'gallery', 'storage'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200056',
    title: 'Diary of Merer — Tura quarry operations',
    description: 'Papyrus records daily quota of limestone blocks from Tura. Names overseer Merer.',
    category: 'Publication',
    primaryClass: 'E4',
    confidence: 92,
    measurementQuality: 88,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0238'],
    locationId: 'LOC-215',
    objectIds: ['OBJ-0227'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['papyri', 'merer', 'tura', 'quarry'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200059',
    title: 'Khafre pyramid — internal passages and chambers',
    description:
      'Two internal chambers: lower rock-cut, upper at pyramid center. Vertical shaft connecting.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 88,
    measurementQuality: 85,
    consensus: 85,
    directObservation: 92,
    status: 'Published',
    sourceIds: ['SRC-0202'],
    locationId: 'LOC-202',
    objectIds: ['OBJ-0202'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khafre', 'passages', 'chambers'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-200060',
    title: 'Menkaure pyramid — G III east chapel',
    description:
      'Eastern chapel of the southernmost subsidiary pyramid. Inscribed reliefs of the queen.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 82,
    measurementQuality: 78,
    consensus: 80,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0227'],
    locationId: 'LOC-205',
    objectIds: ['OBJ-0204'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['menkaure', 'subsidiary', 'chapel', 'relief'],
    version: 1,
    created: '',
    updated: '',
  },
];

export const supplementarySeed = {
  sources,
  locations,
  objects,
  evidence,
};
