import { z } from 'zod';
import { EvidenceSchema } from '@/schemas/evidence';
import { LocationSchema } from '@/schemas/location';
import { ObjectSchema } from '@/schemas/object';
import { SourceSchema } from '@/schemas/source';

export const sources: z.input<typeof SourceSchema>[] = [
  {
    id: 'SRC-0101',
    authors: [{ name: 'W.M.F. Petrie' }],
    title: 'The Pyramids and Temples of Gizeh',
    publication: 'Field & Tuer, London',
    year: 1883,
    type: 'Book',
    reliability: 98,
  },
  {
    id: 'SRC-0102',
    authors: [{ name: 'J.H. Cole' }],
    title: 'Determination of the Exact Size and Orientation of the Great Pyramid of Giza',
    publication: 'Survey of Egypt',
    year: 1925,
    type: 'Government',
    reliability: 99,
  },
  {
    id: 'SRC-0103',
    authors: [{ name: 'G. Dash' }, { name: 'J. Paulson' }],
    title: 'The 2015 Survey of the Base of the Great Pyramid',
    publication: 'Journal of Ancient Egyptian Architecture',
    year: 2016,
    type: 'Journal',
    reliability: 95,
  },
  {
    id: 'SRC-0104',
    authors: [{ name: 'R.W.H. Howard Vyse' }],
    title: 'Operations Carried on at the Pyramids of Gizeh in 1837',
    publication: 'London',
    year: 1841,
    type: 'Book',
    reliability: 85,
  },
  {
    id: 'SRC-0105',
    authors: [{ name: 'R. Gantenbrink' }],
    title: "The Upuaut Project — Robot Survey of King's and Queen's Chamber Shafts",
    publication: 'Self-published',
    year: 1993,
    type: 'Survey',
    reliability: 93,
  },
  {
    id: 'SRC-0106',
    authors: [{ name: 'M. Lehner' }, { name: 'D. Goodman' }],
    title: 'Giza Plateau Mapping Project (GPMP)',
    publication: 'AERA',
    year: 1984,
    type: 'Survey',
    reliability: 94,
  },
  {
    id: 'SRC-0107',
    authors: [{ name: 'ScanPyramids Collaboration' }],
    title: "Discovery of a big void in Khufu's Pyramid by observation of cosmic-ray muons",
    publication: 'Nature',
    year: 2017,
    type: 'Journal',
    reliability: 80,
  },
];

export const locations: z.input<typeof LocationSchema>[] = [
  {
    id: 'LOC-101',
    name: 'Great Pyramid — Exterior',
    parent: undefined,
  },
  {
    id: 'LOC-102',
    name: 'Great Pyramid — Descending Passage',
    parent: 'LOC-101',
  },
  {
    id: 'LOC-103',
    name: 'Great Pyramid — Subterranean Chamber',
    parent: 'LOC-102',
  },
  {
    id: 'LOC-104',
    name: 'Great Pyramid — Ascending Passage',
    parent: 'LOC-101',
  },
  {
    id: 'LOC-105',
    name: 'Great Pyramid — Grand Gallery',
    parent: 'LOC-104',
  },
  {
    id: 'LOC-106',
    name: "Great Pyramid — King's Chamber Complex",
    parent: 'LOC-105',
  },
  {
    id: 'LOC-107',
    name: "Great Pyramid — Queen's Chamber Complex",
    parent: 'LOC-105',
  },
  {
    id: 'LOC-108',
    name: 'Great Pyramid — Relieving Chambers',
    parent: 'LOC-106',
  },
  {
    id: 'LOC-109',
    name: 'Great Pyramid — Shafts',
    parent: 'LOC-101',
  },
];

export const objects: z.input<typeof ObjectSchema>[] = [
  {
    id: 'OBJ-0101',
    name: 'Pyramid Core Masonry',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 98,
    evidence: ['EV-100001', 'EV-100027', 'EV-100028', 'EV-100029', 'EV-100030'],
    sourceIds: ['SRC-0101', 'SRC-0102'],
  },
  {
    id: 'OBJ-0102',
    name: 'Casing Stones (North Face)',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100002'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0103',
    name: 'Original Entrance',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 96,
    evidence: ['EV-100003'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0104',
    name: 'Modern Entrance (Al-Mamun Tunnel)',
    type: 'Architecture',
    objectClass: 'Modern Installations',
    confidence: 100,
    evidence: ['EV-100004'],
    sourceIds: ['SRC-0103'],
  },
  {
    id: 'OBJ-0105',
    name: 'Descending Passage',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 96,
    evidence: ['EV-100005'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0106',
    name: 'Subterranean Chamber',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100006'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0107',
    name: 'Central Pit (Subterranean)',
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 90,
    evidence: ['EV-100007'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0108',
    name: 'Ascending Passage',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100008'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0109',
    name: 'Grand Gallery',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 96,
    evidence: ['EV-100009'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0110',
    name: 'Antechamber',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100010'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0111',
    name: "King's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 97,
    evidence: ['EV-100011'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0112',
    name: "King's Chamber Sarcophagus",
    type: 'ArchaeologicalFind',
    objectClass: 'Archaeological Finds',
    confidence: 97,
    evidence: ['EV-100012'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0113',
    name: "Davison's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100013'],
    sourceIds: ['SRC-0104'],
  },
  {
    id: 'OBJ-0114',
    name: "Wellington's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100014'],
    sourceIds: ['SRC-0104'],
  },
  {
    id: 'OBJ-0115',
    name: "Nelson's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100015'],
    sourceIds: ['SRC-0104'],
  },
  {
    id: 'OBJ-0116',
    name: "Lady Arbuthnot's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100016'],
    sourceIds: ['SRC-0104'],
  },
  {
    id: 'OBJ-0117',
    name: "Campbell's Chamber (with cartouches)",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 90,
    evidence: ['EV-100017'],
    sourceIds: ['SRC-0104'],
  },
  {
    id: 'OBJ-0118',
    name: "Queen's Chamber",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100018'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0119',
    name: "Queen's Chamber Niche",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100019'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0120',
    name: "Queen's Chamber Passage",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 95,
    evidence: ['EV-100020'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0121',
    name: "King's Chamber North Shaft",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 93,
    evidence: ['EV-100021'],
    sourceIds: ['SRC-0105'],
  },
  {
    id: 'OBJ-0122',
    name: "King's Chamber South Shaft",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 93,
    evidence: ['EV-100022'],
    sourceIds: ['SRC-0105'],
  },
  {
    id: 'OBJ-0123',
    name: "Queen's Chamber North Shaft",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 92,
    evidence: ['EV-100023'],
    sourceIds: ['SRC-0105'],
  },
  {
    id: 'OBJ-0124',
    name: "Queen's Chamber South Shaft",
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 92,
    evidence: ['EV-100024'],
    sourceIds: ['SRC-0105'],
  },
  {
    id: 'OBJ-0125',
    name: 'Well Shaft',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 85,
    evidence: ['EV-100025'],
    sourceIds: ['SRC-0101'],
  },
  {
    id: 'OBJ-0126',
    name: 'Grotto',
    type: 'Environmental',
    objectClass: 'Environmental Objects',
    confidence: 80,
    evidence: ['EV-100026'],
    sourceIds: ['SRC-0101'],
  },
];

export const evidence: z.input<typeof EvidenceSchema>[] = [
  {
    id: 'EV-100001',
    title: 'Base dimensions — Cole 1925 survey',
    description:
      'Mean base side 230.364 m measured using invar wires with accuracy ~1:500,000. Maximum variation between surveys ~3.5 cm.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 98,
    measurementQuality: 99,
    consensus: 98,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0102'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0101'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['base', 'dimensions', 'survey'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100002',
    title: 'Casing slope angle — Petrie and Cole measurements',
    description:
      "Slope angle 51°50'40\" ± 1'05\" (Petrie), 51°52' ± 2' (Cole). Seked 5½ palms (14:11 rise:run).",
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 97,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0101', 'SRC-0102'],
    objectIds: ['OBJ-0102'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['casing', 'slope', 'angle'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100003',
    title: 'Original entrance position',
    description:
      'Height 16.97 m above base, offset 7.29 m east of center axis, 24 courses above base on north face.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 96,
    measurementQuality: 97,
    consensus: 96,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0103'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['entrance', 'original'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100004',
    title: 'Al-Mamun tunnel (modern entrance)',
    description:
      '9th century AD tunnel, roughly horizontal, through north face. Now serves as tourist entrance.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 100,
    measurementQuality: 90,
    consensus: 100,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0103'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0104'],
    chronologyTags: [{ period: 'Medieval', scope: 'modification' }],
    tags: ['modern', 'entrance', 'almamun'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100005',
    title: 'Descending Passage — slope and dimensions',
    description:
      'Slope 26°31\'23", total length 105.16 m (floor to Subterranean Chamber), cross-section 1.19 × 1.05 m. Transitions from masonry to bedrock at 33.49 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 96,
    measurementQuality: 97,
    consensus: 96,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-102',
    objectIds: ['OBJ-0105'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['descending', 'passage', 'slope'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100006',
    title: 'Subterranean Chamber — rough-hewn geometry',
    description:
      'Approximately 8.3 m E-W × 5.2 m N-S, roof height ~3.56 m. Very rough, unfinished. Floor irregularity ~0.7 m average.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 85,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-103',
    objectIds: ['OBJ-0106'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['subterranean', 'chamber', 'unfinished'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100007',
    title: 'Central Pit — Subterranean Chamber',
    description:
      'Pit N-S diagonal 2.54 m, depth upper section 1.70 m, total depth below roof 6.73 m, below pavement 33.55 m. Variously interpreted as unfinished sarcophagus recess or cistern.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 85,
    consensus: 80,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-103',
    objectIds: ['OBJ-0107'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['pit', 'subterranean', 'feature'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100008',
    title: 'Ascending Passage — slope and plug blocks',
    description:
      'Slope 26°02\'30", length 39.29 m, cross-section 1.20 × 0.97 m. Three granite plug blocks at lower end. Tura limestone walls.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 97,
    consensus: 95,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-104',
    objectIds: ['OBJ-0108'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['ascending', 'passage', 'plugs'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100009',
    title: 'Grand Gallery — corbelled vault dimensions',
    description:
      'Total sloping length 46.11 m, perpendicular height 8.74 m, width at floor 2.09 m, width at top 1.05 m. 7 corbelled courses, side bench notches, ramp slots.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 96,
    measurementQuality: 97,
    consensus: 96,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-105',
    objectIds: ['OBJ-0109'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['grand-gallery', 'corbel', 'vault'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100010',
    title: 'Antechamber — granite-lined dimensions',
    description:
      'Length 2.954 m, width 1.651 m, height 3.794 m. Granite-lined with portcullis slots and half-width wainscots.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 97,
    consensus: 95,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-106',
    objectIds: ['OBJ-0110'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['antechamber', 'granite', 'portcullis'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100011',
    title: "King's Chamber — precise granite dimensions",
    description:
      'Length 10.47 m, width 5.24 m, height 5.97 m. Walls of Aswan red granite, 5 wall courses. Floor at 42.96 m above base. Joint thickness 1/50 inch (0.5 mm).',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 97,
    measurementQuality: 99,
    consensus: 97,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-106',
    objectIds: ['OBJ-0111'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['kings-chamber', 'granite', 'precise'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100012',
    title: "King's Chamber sarcophagus (coffer)",
    description:
      'Exterior: 2.276 × 0.978 × 1.049 m. Interior: 1.983 × 0.681 × 0.874 m. Aswan red granite. Lid missing. Positioned along west wall, centered E-W.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 97,
    measurementQuality: 99,
    consensus: 97,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-106',
    objectIds: ['OBJ-0112'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['sarcophagus', 'coffer', 'granite'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100013',
    title: "Davison's Chamber — first relieving chamber",
    description:
      'E-W 11.68 m, N-S 5.21 m, height 0.76–1.07 m. Rough granite. Discovered 1765 by Davison.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 80,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0104'],
    locationId: 'LOC-108',
    objectIds: ['OBJ-0113'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['relieving', 'davison'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100014',
    title: "Wellington's Chamber — second relieving chamber",
    description: 'E-W 11.73 m, N-S 5.18 m, height 0.66–1.12 m. Rough granite.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 80,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0104'],
    locationId: 'LOC-108',
    objectIds: ['OBJ-0114'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['relieving', 'wellington'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100015',
    title: "Nelson's Chamber — third relieving chamber",
    description: 'E-W 11.81 m, N-S 5.08 m, height 0.61–1.47 m. Rough granite.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 80,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0104'],
    locationId: 'LOC-108',
    objectIds: ['OBJ-0115'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['relieving', 'nelson'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100016',
    title: "Lady Arbuthnot's Chamber — fourth relieving chamber",
    description: 'E-W 11.38 m, N-S 4.98 m, height 0.41–1.35 m. Rough granite.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 80,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0104'],
    locationId: 'LOC-108',
    objectIds: ['OBJ-0116'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['relieving', 'arbuthnot'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100017',
    title: "Campbell's Chamber — fifth relieving chamber with cartouches",
    description:
      'E-W 11.53 m, N-S 6.25 m, height 1.78–2.62 m. Contains cartouches of Khufu/Khnum-Khuf. Limestone gable roof above.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 90,
    measurementQuality: 80,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0104'],
    locationId: 'LOC-108',
    objectIds: ['OBJ-0117'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['relieving', 'campbell', 'cartouches', 'khufu'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100018',
    title: "Queen's Chamber — dimensions and gabled roof",
    description:
      'Width 5.23 m (N-S), length 5.75 m (E-W), height to wall top 4.69 m, to roof apex 6.23 m. Limestone walls, gabled roof. Floor rough, unfinished.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 97,
    consensus: 95,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-107',
    objectIds: ['OBJ-0118'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['queens-chamber', 'gabled', 'limestone'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100019',
    title: "Queen's Chamber niche — east wall",
    description:
      'Depth 1.04 m, width at base 1.57 m, width at top 0.52 m, height 4.69 m. 4 overlappings. Eccentricity ~0.64 m south of center.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 97,
    consensus: 95,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-107',
    objectIds: ['OBJ-0119'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['niche', 'queens-chamber'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100020',
    title: "Queen's Chamber Passage",
    description:
      'Total length ~43.96 m, breadth ~1.05 m, height before step 1.17 m, beyond step 1.73 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 95,
    consensus: 95,
    directObservation: 98,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-107',
    objectIds: ['OBJ-0120'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['passage', 'queens-chamber'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100021',
    title: "King's Chamber North Shaft — Gantenbrink survey",
    description:
      'Horizontal inlet 2.63 m, cross-section 21×14 cm, mean slope 32°36\', length to exterior 78.43 m. "Door" feature at Block ~21 (Pyramid Rover 2002).',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 93,
    measurementQuality: 95,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0105'],
    locationId: 'LOC-109',
    objectIds: ['OBJ-0121'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['shaft', 'kings-chamber', 'north', 'gantenbrink', 'door'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100022',
    title: "King's Chamber South Shaft — Gantenbrink survey",
    description:
      'Horizontal inlet 1.72 m, cross-section 18×14 cm, mean slope 45°, length to exterior 77.55 m. No door feature.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 93,
    measurementQuality: 95,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0105'],
    locationId: 'LOC-109',
    objectIds: ['OBJ-0122'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['shaft', 'kings-chamber', 'south', 'gantenbrink'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100023',
    title: "Queen's Chamber North Shaft — robot survey",
    description:
      'Horizontal inlet 2.90 m, cross-section 21×21 cm, mean slope 39°. Does not exit pyramid. "Door"/blocking stone found (Pyramid Rover 2002). Lower 92, upper 80 confidence.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 92,
    measurementQuality: 90,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0105'],
    locationId: 'LOC-109',
    objectIds: ['OBJ-0123'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['shaft', 'queens-chamber', 'north', 'door'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100024',
    title: "Queen's Chamber South Shaft — Gantenbrink 1993",
    description:
      'Horizontal inlet 2.88 m, cross-section 21×21 cm, mean slope 39°36\'. Does not exit pyramid. "Door" found by Gantenbrink 1993. Design length to door ~59.6 m.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 92,
    measurementQuality: 93,
    consensus: 88,
    directObservation: 93,
    status: 'Published',
    sourceIds: ['SRC-0105'],
    locationId: 'LOC-109',
    objectIds: ['OBJ-0124'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['shaft', 'queens-chamber', 'south', 'gantenbrink', 'door'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100025',
    title: 'Well Shaft — service shaft dimensions',
    description:
      'Total length ~55 m. Upper entrance in Grand Gallery west wall near floor. Connects to Descending Passage. Irregular vertical and inclined sections.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 85,
    measurementQuality: 80,
    consensus: 85,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-104',
    objectIds: ['OBJ-0125'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['well-shaft', 'service'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100026',
    title: 'Grotto — natural cavity in Well Shaft path',
    description:
      'Natural or modified cavity at bedrock/core interface. Limestone with nummulitic fossils. Height above base ~5.7 m. Irregular dimensions.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 80,
    measurementQuality: 70,
    consensus: 80,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0101'],
    locationId: 'LOC-104',
    objectIds: ['OBJ-0126'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['grotto', 'natural', 'well-shaft'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100027',
    title: 'Khufu pyramid — corner socket stones',
    description:
      'Corner sockets at the four corners of the base. Used for orientation and leveling.',
    category: 'Observation',
    primaryClass: 'E3',
    confidence: 90,
    measurementQuality: 88,
    consensus: 88,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0101', 'SRC-0102'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0101'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khufu', 'corner', 'socket', 'orientation'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100028',
    title: 'Khufu pyramid — pavement foundation',
    description: 'Limestone pavement surrounding the pyramid. Leveled to within millimeters.',
    category: 'Survey',
    primaryClass: 'E2',
    confidence: 92,
    measurementQuality: 95,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0102'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0101'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khufu', 'pavement', 'foundation', 'leveling'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100029',
    title: 'Khufu pyramid — orientation to true north',
    description:
      'Sides oriented to cardinal directions with error ~3\'24". Precision suggests astronomical surveying.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    measurementQuality: 98,
    consensus: 92,
    directObservation: 100,
    status: 'Published',
    sourceIds: ['SRC-0102'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0101'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khufu', 'orientation', 'astronomy', 'cardinal'],
    version: 1,
    created: '',
    updated: '',
  },
  {
    id: 'EV-100030',
    title: 'Khufu pyramid — base levelness',
    description:
      'Pavement leveled to within 2 cm across 230 m. Achieved with water-level or similar.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 93,
    measurementQuality: 95,
    consensus: 90,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0102'],
    locationId: 'LOC-101',
    objectIds: ['OBJ-0101'],
    chronologyTags: [{ period: 'Old Kingdom', scope: 'construction' }],
    tags: ['khufu', 'leveling', 'precision'],
    version: 1,
    created: '',
    updated: '',
  },
];

export const greatPyramidSeed = {
  sources,
  locations,
  objects,
  evidence,
};
