import { z } from 'zod';
import { EvidenceSchema } from '@/schemas/evidence';
import { LocationSchema } from '@/schemas/location';
import { ObjectSchema } from '@/schemas/object';
import { SourceSchema } from '@/schemas/source';

export const sources: z.input<typeof SourceSchema>[] = [
  {
    id: 'SRC-0001',
    authors: [{ name: 'Zahi Hawass' }],
    title: 'The Discovery of the Osiris Shaft at Giza',
    publication:
      "The Archaeology and Art of Ancient Egypt: Essays in Honor of David B. O'Connor, Vol. I",
    year: 2007,
    type: 'Archaeological Report',
    reliability: 95,
  },
  {
    id: 'SRC-0002',
    authors: [{ name: 'Nic Whiting' }],
    title:
      'The Lost Histories of the Shetayet of Sokar: Contextualizing the Osiris Shaft at Rosetau (Giza) in Archaeological History',
    type: 'Survey',
    reliability: 80,
  },
];

export const locations: z.input<typeof LocationSchema>[] = [
  { id: 'LOC-001', name: 'Osiris Shaft' },
  { id: 'LOC-002', name: 'Level 1 — Chamber A', parent: 'LOC-001' },
  { id: 'LOC-003', name: 'Level 2 — Chamber B', parent: 'LOC-001' },
  {
    id: 'LOC-004',
    name: 'Level 3 — Chamber I',
    parent: 'LOC-001',
  },
  { id: 'LOC-005', name: 'Level 3 — Vault and Tunnels', parent: 'LOC-001' },
];

export const objects: z.input<typeof ObjectSchema>[] = [
  {
    id: 'OBJ-0001',
    name: 'Shaft A',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 98,
    evidence: ['EV-000001', 'EV-000010'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0002',
    name: 'Chamber A',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 97,
    evidence: ['EV-000002'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0003',
    name: 'Shaft B',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 98,
    evidence: ['EV-000003', 'EV-000010'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0004',
    name: 'Chamber B',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 97,
    evidence: ['EV-000004'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0005',
    name: 'Shaft C',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 98,
    evidence: ['EV-000005', 'EV-000010'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0006',
    name: 'Chamber I',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 97,
    evidence: ['EV-000006', 'EV-000011'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0007',
    name: 'Central Island',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 96,
    evidence: ['EV-000007'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0008',
    name: 'Basalt Sarcophagus',
    type: 'Artifact',
    objectClass: 'Archaeological Finds',
    confidence: 95,
    evidence: ['EV-000008'],
    sourceIds: ['SRC-0001', 'SRC-0002'],
  },
  {
    id: 'OBJ-0009',
    name: 'Northern Conduit',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 83,
    evidence: ['EV-000009'],
    sourceIds: ['SRC-0001'],
  },
  {
    id: 'OBJ-0010',
    name: 'Niche 2 Sarcophagus',
    type: 'Artifact',
    objectClass: 'Archaeological Finds',
    confidence: 90,
    evidence: ['EV-000012'],
    sourceIds: ['SRC-0001', 'SRC-0002'],
  },
  {
    id: 'OBJ-0011',
    name: 'Niche 7 Sarcophagus',
    type: 'Artifact',
    objectClass: 'Archaeological Finds',
    confidence: 88,
    evidence: ['EV-000013'],
    sourceIds: ['SRC-0001', 'SRC-0002'],
  },
  {
    id: 'OBJ-0012',
    name: 'Chamber B Eastern Passage',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 75,
    evidence: ['EV-000014'],
    sourceIds: ['SRC-0002'],
  },
  {
    id: 'OBJ-0013',
    name: 'East Corridor',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 70,
    evidence: ['EV-000015'],
    sourceIds: ['SRC-0002'],
  },
  {
    id: 'OBJ-0014',
    name: 'Vault',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 70,
    evidence: ['EV-000016'],
    sourceIds: ['SRC-0002'],
  },
  {
    id: 'OBJ-0015',
    name: 'Eastern Tunnel',
    type: 'Architecture',
    objectClass: 'Original Architecture',
    confidence: 65,
    evidence: ['EV-000017'],
    sourceIds: ['SRC-0002'],
  },
];

export const evidence: z.input<typeof EvidenceSchema>[] = [
  {
    id: 'EV-000001',
    title: 'Shaft A entrance cross-section and depth',
    description: 'Entrance opening approximately 2.60 m × 3.00 m; vertical depth 9.62 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 98,
    confidenceBasis: 'Direct survey in Hawass 2007.',
    measurementQuality: 98,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-001',
    objectIds: ['OBJ-0001'],
  },
  {
    id: 'EV-000002',
    title: 'Chamber A dimensions',
    description: 'Length 8.60 m, maximum width 3.85 m, maximum height 2.70 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 97,
    confidenceBasis: 'Surveyed in Hawass 2007.',
    measurementQuality: 97,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-002',
    objectIds: ['OBJ-0002'],
  },
  {
    id: 'EV-000003',
    title: 'Shaft B mouth and depth',
    description: 'Mouth cross-section 1.90 m × 1.90 m; depth 13.25 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 98,
    confidenceBasis: 'Surveyed in Hawass 2007.',
    measurementQuality: 98,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-002',
    objectIds: ['OBJ-0003'],
  },
  {
    id: 'EV-000004',
    title: 'Chamber B dimensions',
    description: 'Length 6.80 m (N–S), width 3.65 m (E–W), height 2.60 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 97,
    confidenceBasis: 'Surveyed in Hawass 2007.',
    measurementQuality: 97,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-003',
    objectIds: ['OBJ-0004'],
  },
  {
    id: 'EV-000005',
    title: 'Shaft C dimensions',
    description: 'North–South 1.65 m, East–West 1.90 m, depth 7.50 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 98,
    confidenceBasis: 'Surveyed in Hawass 2007.',
    measurementQuality: 98,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-003',
    objectIds: ['OBJ-0005'],
  },
  {
    id: 'EV-000006',
    title: 'Chamber I wall lengths',
    description: 'Eastern 8.84 m, Southern 8.60 m, Western 9.08 m, Northern 9.20 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 97,
    confidenceBasis: 'Surveyed in Hawass 2007.',
    measurementQuality: 97,
    consensus: 95,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-004',
    objectIds: ['OBJ-0006'],
  },
  {
    id: 'EV-000007',
    title: 'Central emplacement (island) dimensions',
    description: 'Approximate 5.2 m × 3.2 m island with wall thickness c. 2.00 m.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 96,
    confidenceBasis: 'Surveyed in Hawass 2007; rounded summary dimensions.',
    measurementQuality: 95,
    consensus: 90,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-004',
    objectIds: ['OBJ-0007'],
  },
  {
    id: 'EV-000008',
    title: 'Basalt sarcophagus dimensions',
    description:
      'Exterior length 228 cm, exterior width 108 cm; interior length 200 cm, interior width 72 cm.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 95,
    confidenceBasis: 'Whiting thesis; Hawass confirms approximate exterior length.',
    measurementQuality: 95,
    consensus: 90,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0001', 'SRC-0002'],
    locationId: 'LOC-004',
    objectIds: ['OBJ-0008'],
  },
  {
    id: 'EV-000009',
    title: 'Northern conduit accessible extent',
    description:
      'Entry cross-section 0.5–0.6 m by 0.5–0.7 m; accessible length 6.0–7.0 m before obstruction.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 83,
    confidenceBasis: 'Partial exploration; termination choked with mud and groundwater.',
    measurementQuality: 80,
    consensus: 70,
    directObservation: 85,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-004',
    objectIds: ['OBJ-0009'],
  },
  {
    id: 'EV-000010',
    title: 'Total vertical depth of the Osiris Shaft',
    description:
      'Sum of Shaft A, B, and C depths: 9.62 + 13.25 + 7.50 = 30.37 m. The Level 2 floor is 0.28 m below the bottom of Shaft B, so the Level 3 floor lies at approximately 30.65 m below the causeway entrance.',
    category: 'Measurement',
    primaryClass: 'E2',
    confidence: 98,
    confidenceBasis: 'Derived from surveyed shaft depths in Hawass 2007.',
    measurementQuality: 98,
    consensus: 95,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-001',
    objectIds: ['OBJ-0001', 'OBJ-0003', 'OBJ-0005'],
  },
  {
    id: 'EV-000011',
    title: 'Level 3 flooded condition',
    description: 'Chamber I is seasonally or permanently flooded by groundwater infiltration.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 90,
    confidenceBasis: 'Repeated observation during excavation and later visits.',
    measurementQuality: 80,
    consensus: 85,
    directObservation: 95,
    status: 'Published',
    sourceIds: ['SRC-0001'],
    locationId: 'LOC-004',
    objectIds: ['OBJ-0006'],
  },
  {
    id: 'EV-000012',
    title: 'Granite sarcophagus in Chamber B niche 2',
    description:
      'Massive granite sarcophagus in niche no. 2 containing human bone remains and teeth. The coffin blocks an 80 × 100 cm passage leading east toward the Valley Temple and the Sphinx.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 90,
    confidenceBasis: 'Direct observation by Spörri; Hawass confirms presence of sarcophagi.',
    measurementQuality: 85,
    consensus: 80,
    directObservation: 90,
    status: 'Published',
    sourceIds: ['SRC-0001', 'SRC-0002'],
    locationId: 'LOC-003',
    objectIds: ['OBJ-0010'],
  },
  {
    id: 'EV-000013',
    title: 'Empty granite sarcophagus in Chamber B niche 7',
    description: 'Granite sarcophagus in niche no. 7, found empty.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 88,
    confidenceBasis: 'Direct observation by Spörri.',
    measurementQuality: 85,
    consensus: 75,
    directObservation: 88,
    status: 'Published',
    sourceIds: ['SRC-0001', 'SRC-0002'],
    locationId: 'LOC-003',
    objectIds: ['OBJ-0011'],
  },
  {
    id: 'EV-000014',
    title: 'Blocked eastern passage from Chamber B',
    description:
      'An 80 × 100 cm passage leads east from Chamber B toward the Valley Temple and Sphinx, blocked by the sarcophagus from niche 2 which was forced into the passage.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 75,
    confidenceBasis: 'Observed by Spörri; passage blocked and unexplored beyond.',
    measurementQuality: 70,
    consensus: 60,
    directObservation: 80,
    status: 'Published',
    sourceIds: ['SRC-0002'],
    locationId: 'LOC-003',
    objectIds: ['OBJ-0012'],
  },
  {
    id: 'EV-000015',
    title: 'Narrow east corridor from Chamber I',
    description:
      'A narrow corridor leads east from Chamber I approximately 20 m into the underworld to a small vault.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 70,
    confidenceBasis: 'Explored by Spörri; corridor is narrow and difficult to traverse.',
    measurementQuality: 65,
    consensus: 55,
    directObservation: 75,
    status: 'Published',
    sourceIds: ['SRC-0002'],
    locationId: 'LOC-005',
    objectIds: ['OBJ-0013'],
  },
  {
    id: 'EV-000016',
    title: 'Small vault at end of east corridor',
    description:
      'A small vault at the end of the east corridor, barely large enough to turn around in. Two narrow tunnels branch from here: one north toward the Great Pyramid and one east toward the Sphinx.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 70,
    confidenceBasis: 'Direct observation by Spörri.',
    measurementQuality: 65,
    consensus: 55,
    directObservation: 75,
    status: 'Published',
    sourceIds: ['SRC-0002'],
    locationId: 'LOC-005',
    objectIds: ['OBJ-0014'],
  },
  {
    id: 'EV-000017',
    title: 'Eastern tunnel toward the Sphinx',
    description:
      'A 40 × 40 cm shaft leading east from the vault in the direction of the Sphinx. Too small for adults to explore; unexplored beyond initial accessible extent.',
    category: 'Observation',
    primaryClass: 'E1',
    confidence: 65,
    confidenceBasis: 'Observed by Spörri; exploration abandoned due to size constraints.',
    measurementQuality: 60,
    consensus: 50,
    directObservation: 70,
    status: 'Published',
    sourceIds: ['SRC-0002'],
    locationId: 'LOC-005',
    objectIds: ['OBJ-0015'],
  },
];

export interface SeedData {
  sources: z.input<typeof SourceSchema>[];
  locations: z.input<typeof LocationSchema>[];
  objects: z.input<typeof ObjectSchema>[];
  evidence: z.input<typeof EvidenceSchema>[];
}

export const osirisSeed: SeedData = {
  sources,
  locations,
  objects,
  evidence,
};
