import type { AssetDefinition } from './assetDefinitions';

/** Auto-generated from database/blockouts/great-pyramid.ts */
export const GREAT_PYRAMID_ASSETS: AssetDefinition[] = [
  {
    id: 'GP-OBJ-0101-LOD0',
    name: 'Pyramid Exterior (core masonry)',
    monument: 'GP',
    location: 'Exterior',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100001'],
    sourceIds: ['SRC-0101', 'SRC-0102'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0101-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0102-LOD0',
    name: 'Casing Stones (north face, lower courses)',
    monument: 'GP',
    location: 'Exterior',
    objectClass: 'Hero',
    materialId: 'MAT_TuraLimestone',
    evidenceIds: ['EV-100002'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0102-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0103-LOD0',
    name: 'Original Entrance',
    monument: 'GP',
    location: 'Exterior',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100003'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0103-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0104-LOD0',
    name: 'Modern Entrance (Al-Mamun Tunnel)',
    monument: 'GP',
    location: 'Exterior',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100004', 'EV-100008'],
    sourceIds: ['SRC-0103', 'SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0104-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0105-LOD0',
    name: 'Descending Passage (sloped)',
    monument: 'GP',
    location: 'Passages',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100005'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0105-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0106-LOD0',
    name: 'Subterranean Chamber',
    monument: 'GP',
    location: 'Subterranean',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100006'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0106-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0107-LOD0',
    name: 'Central Pit (Subterranean)',
    monument: 'GP',
    location: 'Subterranean',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100007'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0107-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0108-LOD0',
    name: 'Ascending Passage',
    monument: 'GP',
    location: 'Passages',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100008'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0108-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0109-LOD0',
    name: 'Grand Gallery',
    monument: 'GP',
    location: 'GrandGallery',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100009'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0109-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0110-LOD0',
    name: 'Antechamber',
    monument: 'GP',
    location: 'KingsComplex',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100010'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0110-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0111-LOD0',
    name: "King's Chamber",
    monument: 'GP',
    location: 'KingsComplex',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100011'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0111-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0112-LOD0',
    name: "King's Chamber Sarcophagus",
    monument: 'GP',
    location: 'KingsComplex',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100012'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0112-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0113-LOD0',
    name: "Davison's Chamber (Relieving 1)",
    monument: 'GP',
    location: 'RelievingChambers',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100013'],
    sourceIds: ['SRC-0104'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0113-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0114-LOD0',
    name: "Wellington's Chamber (Relieving 2)",
    monument: 'GP',
    location: 'RelievingChambers',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100014'],
    sourceIds: ['SRC-0104'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0114-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0115-LOD0',
    name: "Nelson's Chamber (Relieving 3)",
    monument: 'GP',
    location: 'RelievingChambers',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100015'],
    sourceIds: ['SRC-0104'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0115-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0116-LOD0',
    name: "Lady Arbuthnot's Chamber (Relieving 4)",
    monument: 'GP',
    location: 'RelievingChambers',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100016'],
    sourceIds: ['SRC-0104'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0116-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0117-LOD0',
    name: "Campbell's Chamber (Relieving 5, with cartouches)",
    monument: 'GP',
    location: 'RelievingChambers',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100017'],
    sourceIds: ['SRC-0104'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0117-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0118-LOD0',
    name: "Queen's Chamber",
    monument: 'GP',
    location: 'QueensComplex',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100018'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0118-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0119-LOD0',
    name: "Queen's Chamber Niche (East Wall)",
    monument: 'GP',
    location: 'QueensComplex',
    objectClass: 'Hero',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100019'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0119-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0120-LOD0',
    name: "Queen's Chamber Passage",
    monument: 'GP',
    location: 'Passages',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100020'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0120-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0121-LOD0',
    name: 'KC North Shaft',
    monument: 'GP',
    location: 'Other',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100021'],
    sourceIds: ['SRC-0105'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0121-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0122-LOD0',
    name: 'KC South Shaft',
    monument: 'GP',
    location: 'Other',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100022'],
    sourceIds: ['SRC-0105'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0122-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0123-LOD0',
    name: 'QC North Shaft',
    monument: 'GP',
    location: 'Other',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100023'],
    sourceIds: ['SRC-0105'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0123-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0124-LOD0',
    name: 'QC South Shaft',
    monument: 'GP',
    location: 'Other',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100024'],
    sourceIds: ['SRC-0105'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0124-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0125-LOD0',
    name: 'Well Shaft',
    monument: 'GP',
    location: 'Other',
    objectClass: 'Standard',
    materialId: 'MAT_LocalLimestone',
    evidenceIds: ['EV-100025'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0125-LOD0.glb',
  },
  {
    id: 'GP-OBJ-0126-LOD0',
    name: 'Grotto',
    monument: 'GP',
    location: 'Passages',
    objectClass: 'Standard',
    materialId: 'MAT_Bedrock',
    evidenceIds: ['EV-100026'],
    sourceIds: ['SRC-0101'],
    confidence: 95,
    lods: ['LOD0', 'LOD1'],
    filePath: 'assets/export/glB/objects/GP-OBJ-0126-LOD0.glb',
  },
];

export function getGreatPyramidAssets(): AssetDefinition[] {
  return [...GREAT_PYRAMID_ASSETS];
}
